# Generated by Django 6.0.6 on 2026-07-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the financial goal', max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='The future target amount to achieve', max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='The current progress or recent status towards the target', max_digits=12)),
                ('start_date', models.DateField(help_text='The start date for tracking this goal')),
                ('end_date', models.DateField(help_text='The target completion date for this goal')),
                ('category', models.CharField(blank=True, help_text='Optional category this goal is linked to (e.g. Shopping, Housing)', max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('achieved', 'Achieved'), ('failed', 'Failed')], default='ongoing', help_text='Current tracking status of the goal', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed context or strategy for this goal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Type of transaction: income or expense', max_length=10)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Investment', 'Investment'), ('Food & Dining', 'Food & Dining'), ('Rent & Housing', 'Rent & Housing'), ('Utilities', 'Utilities'), ('Entertainment & Leisure', 'Entertainment & Leisure'), ('Transportation', 'Transportation'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Shopping', 'Shopping'), ('Other', 'Other')], default='Other', help_text='Financial category of the transaction', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monetary value of the transaction', max_digits=12)),
                ('date', models.DateField(help_text='Date when the transaction occurred')),
                ('description', models.TextField(blank=True, help_text='Notes/details about this transaction', null=True)),
                ('account_bank', models.CharField(default='General Account', help_text='The bank account, card, or method used for this record', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='System timestamp when this record was created')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
