# Generated by Django 6.0.6 on 2026-07-11 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='bank_statements/')),
                ('original_filename', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('statement_period_start', models.DateField(blank=True, null=True)),
                ('statement_period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('review_pending', 'Review Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('total_transactions_extracted', models.IntegerField(default=0)),
                ('total_transactions_imported', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('debt_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('personal_loan', 'Personal Loan'), ('mortgage', 'Mortgage'), ('auto_loan', 'Auto Loan'), ('student_loan', 'Student Loan'), ('medical_debt', 'Medical Debt'), ('other', 'Other')], max_length=20)),
                ('creditor', models.CharField(max_length=100)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted'), ('in_grace', 'In Grace Period')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quick_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cash_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('net_profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('debt_to_income', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('debt_to_asset', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('income_growth_yoy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('expense_growth_yoy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('net_worth_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('expenses_per_category', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_description', models.TextField()),
                ('cleaned_description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('suggested_category', models.CharField(choices=[('Salary', 'Salary'), ('Investment', 'Investment'), ('Food & Dining', 'Food & Dining'), ('Rent & Housing', 'Rent & Housing'), ('Utilities', 'Utilities'), ('Entertainment & Leisure', 'Entertainment & Leisure'), ('Transportation', 'Transportation'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Shopping', 'Shopping'), ('Other', 'Other')], default='Other', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('user_confirmed_category', models.CharField(blank=True, choices=[('Salary', 'Salary'), ('Investment', 'Investment'), ('Food & Dining', 'Food & Dining'), ('Rent & Housing', 'Rent & Housing'), ('Utilities', 'Utilities'), ('Entertainment & Leisure', 'Entertainment & Leisure'), ('Transportation', 'Transportation'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Shopping', 'Shopping'), ('Other', 'Other')], max_length=50, null=True)),
                ('user_confirmed_type', models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('unknown', 'Unknown')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_transactions', to='finance_api.bankstatement')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
