# Generated by Django 6.0.6 on 2026-07-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0002_bankstatement_debt_financialsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='account_bank_other',
            field=models.CharField(blank=True, help_text="Specify custom account/method when 'Other' is selected", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='file',
            field=models.FileField(upload_to='media/bank_statements/'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='account_bank',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash_loan', 'Cash Loan'), ('bank_loan', 'Bank Loan'), ('cash', 'Cash'), ('business_card', 'Business Card'), ('bre_b', 'Bre-B (Employee Special Card)'), ('other', 'Other')], default='cash', help_text='The bank account, card, or method used for this record', max_length=50),
        ),
    ]
