# Generated by Django 6.0.6 on 2026-07-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0003_financialrecord_account_bank_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of file content for duplicate detection', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='statement_type',
            field=models.CharField(choices=[('savings', 'Savings Account'), ('checking', 'Checking Account'), ('credit_card', 'Credit Card'), ('loan', 'Loan Statement'), ('investment', 'Investment Account'), ('other', 'Other')], default='other', help_text='Type of statement: savings, checking, credit_card, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='file',
            field=models.FileField(upload_to='bank_statements/'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['content_hash'], name='finance_api_content_dd2434_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['statement_type', 'statement_period_start', 'statement_period_end'], name='finance_api_stateme_12fa39_idx'),
        ),
    ]
