# Generated by Django 6.0.6 on 2026-07-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0004_bankstatement_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='password',
            field=models.CharField(blank=True, help_text='Password if the file has one', max_length=100, null=True),
        ),
    ]
