# Generated by Django 6.0.6 on 2026-07-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0006_customcategory_categorizationmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.AlterField(
            model_name='categorizationmemory',
            name='transaction_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customcategory',
            name='transaction_type',
            field=models.CharField(default='expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='extractedtransaction',
            name='suggested_category',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='extractedtransaction',
            name='transaction_type',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='extractedtransaction',
            name='user_confirmed_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extractedtransaction',
            name='user_confirmed_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(default='Other', help_text='Financial category of the transaction', max_length=50),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='type',
            field=models.CharField(help_text='Type of transaction: income, expense, or custom', max_length=10),
        ),
    ]
