# Generated by Django 6.0.6 on 2026-07-26 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0007_customtype_usersetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('choice_type', models.CharField(choices=[('category', 'Category'), ('type', 'Transaction Type')], max_length=20)),
                ('transaction_type', models.CharField(blank=True, default='expense', max_length=10)),
                ('builtin', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='finance_api.customcategory')),
                ('custom_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='finance_api.customtype')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('name', 'choice_type')},
            },
        ),
    ]
