# Generated by Django 6.0.6 on 2026-07-26 23:36

from django.db import migrations


CATEGORY_CHOICES = [
    'Salary', 'Investment', 'Food & Dining', 'Rent & Housing',
    'Utilities', 'Entertainment & Leisure', 'Transportation',
    'Healthcare', 'Education', 'Shopping', 'Other',
]

RECORD_TYPES = ['income', 'expense']


def seed_choices(apps, schema_editor):
    Choice = apps.get_model('finance_api', 'Choice')
    CustomType = apps.get_model('finance_api', 'CustomType')
    CustomCategory = apps.get_model('finance_api', 'CustomCategory')

    for i, name in enumerate(CATEGORY_CHOICES):
        Choice.objects.create(
            name=name, choice_type='category',
            transaction_type='expense', builtin=True, sort_order=i
        )

    for i, name in enumerate(RECORD_TYPES):
        Choice.objects.create(
            name=name, choice_type='type',
            builtin=True, sort_order=i
        )

    for ct in CustomType.objects.all():
        Choice.objects.create(
            name=ct.name, choice_type='type',
            builtin=False, custom_type=ct
        )

    for cc in CustomCategory.objects.all():
        Choice.objects.create(
            name=cc.name, choice_type='category',
            transaction_type=cc.transaction_type,
            builtin=False, custom_category=cc
        )


def reverse_seed(apps, schema_editor):
    Choice = apps.get_model('finance_api', 'Choice')
    Choice.objects.filter(builtin=True).delete()
    Choice.objects.filter(custom_type__isnull=False).delete()
    Choice.objects.filter(custom_category__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0008_choice_model'),
    ]

    operations = [
        migrations.RunPython(seed_choices, reverse_seed),
    ]
