# Generated by Django 6.0.6 on 2026-07-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0009_seed_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsnapshot',
            name='net_worth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='total_assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='total_liabilities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
