# Generated by Django 6.0.6 on 2026-08-02 13:08

import django.core.validators
from django.db import migrations, models


def due_dates_to_day(apps, schema_editor):
    """Convert each debt's due_date from a full date to its day-of-month.

    Runs BEFORE the column rebuild: rewriting the column with a bare numeric
    string means SQLite's INTEGER affinity stores it as a real integer.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE finance_api_debt "
            "SET due_date = CAST(strftime('%d', due_date) AS INTEGER)"
        )


def days_to_due_dates(apps, schema_editor):
    """Reverse: restore the day-of-month back into a neutral date."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE finance_api_debt "
            "SET due_date = printf('2000-01-%02d', CAST(due_date AS INTEGER))"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0010_financialsnapshot_net_worth_and_more'),
    ]

    operations = [
        migrations.RunPython(due_dates_to_day, days_to_due_dates),
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.PositiveSmallIntegerField(help_text='Day of month the payment is due (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]