# Generated by Django 6.0.6 on 2026-08-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0011_alter_debt_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='ai_keys',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='ai_model',
            field=models.CharField(blank=True, default='', help_text="Model name override; defaults to the provider's default model when empty", max_length=100),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Gemini (Google)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='gemini', max_length=20),
        ),
    ]
