# Generated by Django 6.0.6 on 2026-08-22 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0012_usersetting_ai_keys_usersetting_ai_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='ISO 4217 currency code (e.g. USD, EUR). COP is the base currency and is not stored.', max_length=3, unique=True)),
                ('rate_to_cop', models.DecimalField(decimal_places=4, help_text='Exchange rate: how many COP one unit of this currency is worth. E.g. 4000.0000 means 1 USD = 4,000 COP.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['currency_code'],
            },
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='currency',
            field=models.CharField(default='COP', help_text='ISO 4217 currency code of the statement (e.g. COP, USD, EUR). Editable after extraction.', max_length=3),
        ),
        migrations.AddField(
            model_name='debt',
            name='currency',
            field=models.CharField(default='COP', help_text='ISO 4217 currency code for this debt (e.g. COP, USD, EUR)', max_length=3),
        ),
        migrations.AddField(
            model_name='extractedtransaction',
            name='currency',
            field=models.CharField(default='COP', help_text='ISO 4217 currency code of this transaction (inherits from statement, editable in review)', max_length=3),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='currency',
            field=models.CharField(default='COP', help_text='ISO 4217 currency code of the amount', max_length=3),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='currency',
            field=models.CharField(default='COP', max_length=10),
        ),
    ]
