# Generated by Django 6.0.6 on 2026-09-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0012_usersetting_ai_keys_usersetting_ai_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Gemini (Google)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='ai_provider', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
