# Generated by Django 6.0.6 on 2026-08-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0014_dailyusersnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtransaction',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Amount converted to USD using the user's active DailyUserSnapshot rate", max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code of the statement (e.g. COP, USD, EUR). Editable after extraction.', max_length=3),
        ),
        migrations.AlterField(
            model_name='extractedtransaction',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code of this transaction (inherits from statement, editable in review)', max_length=3),
        ),
    ]
