# Generated by Django 6.0.6 on 2026-08-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0015_extractedtransaction_usd_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='totals_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time usd_amount values on extracted transactions were refreshed via live rates.', null=True),
        ),
    ]
