# Generated by Django 5.2.17 on 2026-09-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_api", "0015_harden_owner_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersetting",
            name="backup_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="E.164 format, e.g. +573001234567",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="sms_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="totp_last_step",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="totp_secret",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="two_factor_method",
            field=models.CharField(
                blank=True,
                choices=[("totp", "Authenticator app"), ("sms", "SMS")],
                default="",
                max_length=10,
            ),
        ),
    ]
