# Generated by Django 5.2.17 on 2026-09-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_api", "0016_two_factor_and_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 code, e.g. COP, USD, EUR",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("symbol", models.CharField(blank=True, default="", max_length=8)),
                ("decimals", models.PositiveSmallIntegerField(default=2)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive currencies stay readable but are not offered in pickers",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="debt",
            name="currency",
            field=models.CharField(
                default="COP",
                help_text="ISO 4217 code for every amount on this debt",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="expectedgoal",
            name="currency",
            field=models.CharField(
                default="COP",
                help_text="ISO 4217 code for both amounts above",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="currency",
            field=models.CharField(
                default="COP",
                help_text="ISO 4217 code of the amount above",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="currency",
            field=models.CharField(default="COP", max_length=10),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base", models.CharField(db_index=True, max_length=3)),
                ("target", models.CharField(db_index=True, max_length=3)),
                ("rate", models.DecimalField(decimal_places=12, max_digits=24)),
                (
                    "rate_date",
                    models.DateField(
                        help_text="The day this rate is published for (provider's own date)"
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(blank=True, default="", max_length=40)),
            ],
            options={
                "ordering": ["-rate_date", "base", "target"],
                "indexes": [
                    models.Index(
                        fields=["base", "target", "-rate_date"],
                        name="finance_api_base_6aa1bf_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("base", "target", "rate_date"),
                        name="uniq_rate_base_target_date",
                    )
                ],
            },
        ),
    ]
