# Generated by Django 6.0.6 on 2026-08-30 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0016_add_totals_updated_at_to_bankstatement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='owner',
            field=models.ForeignKey(help_text='The user who uploaded this statement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debt',
            name='owner',
            field=models.ForeignKey(help_text='The user this debt belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expectedgoal',
            name='owner',
            field=models.ForeignKey(help_text='The user this goal belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='owner',
            field=models.ForeignKey(help_text='The user this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='owner',
            field=models.ForeignKey(help_text='The user this monthly snapshot belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialsnapshot',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='financialsnapshot',
            unique_together={('owner', 'date')},
        ),
    ]
