# Generated by Django 6.0.6 on 2026-08-30 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0018_backfill_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='owner',
            field=models.ForeignKey(help_text='The user who uploaded this statement', on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debt',
            name='owner',
            field=models.ForeignKey(help_text='The user this debt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expectedgoal',
            name='owner',
            field=models.ForeignKey(help_text='The user this goal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='owner',
            field=models.ForeignKey(help_text='The user this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialsnapshot',
            name='owner',
            field=models.ForeignKey(help_text='The user this monthly snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to=settings.AUTH_USER_MODEL),
        ),
    ]
