# Generated by Django 5.2.17 on 2026-09-05 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_api", "0018_seed_currencies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("savings", "Savings Account"),
                            ("investment", "Investment"),
                            ("retirement", "Retirement Fund"),
                            ("property", "Property"),
                            ("vehicle", "Vehicle"),
                            ("business", "Business Stake"),
                            ("receivable", "Money Owed to Me"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "currency",
                    models.CharField(
                        default="COP",
                        help_text="ISO 4217 code the value above is expressed in",
                        max_length=3,
                    ),
                ),
                (
                    "is_liquid",
                    models.BooleanField(
                        default=False,
                        help_text="Convertible to cash within days; drives the emergency-fund metrics",
                    ),
                ),
                (
                    "valued_at",
                    models.DateField(
                        blank=True,
                        help_text="When this valuation was taken — a stale one quietly distorts net worth",
                        null=True,
                    ),
                ),
                ("acquired_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user this asset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-current_value", "name"],
            },
        ),
    ]
