# Generated by Django 6.0.6 on 2026-08-30 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0019_make_owner_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of file content for duplicate detection (unique per owner, see Meta)', max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bankstatement',
            unique_together={('owner', 'content_hash')},
        ),
    ]
