# Generated by Django 5.2.17 on 2026-09-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_api", "0019_asset_registry"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialsnapshot",
            name="emergency_fund_months",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Months of essential spending the liquid assets would cover",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="financialsnapshot",
            name="liquid_assets",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Assets convertible to cash within days, at this month's close",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="net_worth",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_assets",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_liabilities",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
