# Generated by Django 6.0.6 on 2026-08-30 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0020_statement_content_hash_per_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorizationmemory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categorizationmemory',
            name='owner',
            field=models.ForeignKey(help_text='The user whose confirmations produced this pattern', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorization_memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owning user; NULL for built-in choices (builtin=True), which are shared', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customcategory',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owning user; NULL for the shared built-in vocabulary', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customtype',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owning user; NULL for the shared built-in vocabulary', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='owner',
            field=models.OneToOneField(help_text='The user these settings belong to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='categorizationmemory',
            unique_together={('owner', 'pattern', 'category', 'transaction_type')},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('owner', 'name', 'choice_type')},
        ),
        migrations.AlterUniqueTogether(
            name='customcategory',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customtype',
            unique_together={('owner', 'name')},
        ),
    ]
