# Generated by Django 5.2.17 on 2026-09-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_api", "0020_wealthness_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="expectedgoal",
            name="experience_date",
            field=models.DateField(
                blank=True,
                help_text="When the experience takes place, if it has a fixed date",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expectedgoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("savings", "Savings"),
                    ("experience", "Life Experience"),
                    ("emergency_fund", "Emergency Fund"),
                    ("debt_payoff", "Debt Payoff"),
                    ("purchase", "Purchase"),
                    ("other", "Other"),
                ],
                default="savings",
                help_text="Experience goals can carry an itemised budget",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="expectedgoal",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Where the experience takes place",
                max_length=120,
            ),
        ),
        migrations.CreateModel(
            name="ExperienceBudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("lodging", "Lodging"),
                            ("food", "Food"),
                            ("activities", "Activities"),
                            ("insurance", "Insurance & Visas"),
                            ("shopping", "Shopping"),
                            ("buffer", "Buffer"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Filled in once the money is actually spent",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="COP", max_length=3)),
                (
                    "is_booked",
                    models.BooleanField(
                        default=False,
                        help_text="Already paid or reserved, so the price will not move",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        help_text="The experience this line belongs to; ownership follows it",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_items",
                        to="finance_api.expectedgoal",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "label"],
            },
        ),
    ]
