# Generated by Django 5.2.17 on 2026-09-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_api", "0021_life_experiences"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialsnapshot",
            name="conversion_complete",
            field=models.BooleanField(
                default=True,
                help_text="False when an amount could not be converted to the base currency and was excluded from this snapshot's figures",
            ),
        ),
    ]
