# Generated by Django 6.0.6 on 2026-09-06 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0013_alter_bankstatement_bank_name_and_more'),
        ('finance_api', '0022_financialsnapshot_conversion_complete'),
    ]

    operations = [
    ]
