# Generated by Django 6.0.6 on 2026-08-30 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0022_backfill_phase0b_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='owner',
            field=models.OneToOneField(help_text='The user these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='setting', to=settings.AUTH_USER_MODEL),
        ),
    ]
