"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import os
import sys

BASE_DIR = Path(__file__).resolve().parent.parent

# True while `manage.py test` runs. Used to relax settings the test client
# cannot satisfy (auth throttling, the HTTPS redirect).
_TESTING = 'test' in sys.argv

load_dotenv(BASE_DIR / '.env')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')

# Exchange rates. This key is server-wide on purpose: the USD->COP rate is the
# same for every account, so one key and one shared cache serve everyone.
# (The AI keys are per user instead, because each person spends their own
# quota.) Get one free at https://www.exchangerate-api.com/
EXCHANGERATE_API_KEY = os.getenv('EXCHANGERATE_API_KEY', '')
FX_PROVIDER = os.getenv('FX_PROVIDER', 'exchangerate-api')


def env_flag(name, default):
    """Read a boolean environment variable ('1', 'true' and 'yes' are true)."""
    return os.environ.get(name, default).lower() in ('1', 'true', 'yes')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag('DJANGO_DEBUG', 'true')

# The secret key signs sessions and JWTs, and derives the Fernet key that
# encrypts stored AI provider keys (see finance_api/crypto.py) — so it must be
# set AND stay stable outside local development: changing it makes previously
# stored keys undecryptable. `.env` is gitignored; generate one with:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off. '
            'Generate one with: python -c "from django.core.management.utils '
            'import get_random_secret_key; print(get_random_secret_key())"'
        )
    # Development only. Kept as the historical literal so AI keys already
    # encrypted on a local machine stay readable; it is never used when
    # DEBUG is off.
    SECRET_KEY = 'django-insecure-%u8f@dcxb)rtlv#2ee59#5srfid4av(7(l4xu&&hevz3zu6tx!'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'corsheaders',
    'finance_api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# The initial migrations were generated with BigAutoField primary keys. Keeping
# this explicit stops Django from proposing a downgrade to AutoField on every
# makemigrations run (and silences the matching W042 checks).
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os

DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite')

if DB_ENGINE == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'personal_finance'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '3306'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.environ.get('DB_NAME', 'db.sqlite3'),
        }
    }

# CORS Configuration
# Only the local Vite dev server is allowed; override via CORS_ALLOWED_ORIGINS.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174',
    ).split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = False


# Production hardening. Left off in development so `runserver` keeps working
# over plain HTTP, and during tests because the test client speaks HTTP and
# would only ever see 301s. Each flag can be overridden when a deployment
# needs it (for example SECURE_SSL_REDIRECT=false while TLS terminates
# upstream).
if not DEBUG and not _TESTING:
    SECURE_SSL_REDIRECT = env_flag('SECURE_SSL_REDIRECT', 'true')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Tell Django a request is HTTPS when the proxy in front of it says so.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS: start low (a day) and raise it once HTTPS is proven stable —
    # browsers remember this value and will refuse plain HTTP until it expires.
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '86400'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_flag('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'true')
    SECURE_HSTS_PRELOAD = env_flag('SECURE_HSTS_PRELOAD', 'false')
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# REST Framework: JWT authentication on every endpoint by default.
# Login / register are AllowAny explicitly, with per-scope throttling.
# During test runs throttling is disabled so the suite never trips limits.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_RATES': {
        'login': None if _TESTING else os.environ.get('THROTTLE_LOGIN', '10/min'),
        'register': None if _TESTING else os.environ.get('THROTTLE_REGISTER', '10/hour'),
        # A 6-digit code is only a million combinations: without a limit it
        # falls to brute force in minutes.
        'mfa': None if _TESTING else os.environ.get('THROTTLE_MFA', '10/min'),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Personal Finance API',
    'DESCRIPTION': (
        'REST API for the Personal Financial App: financial records, bank statement '
        'PDF extraction, debts, goals, analytics snapshots, exports, and AI-powered '
        'analysis, categorization and chat (Gemini / OpenAI / Anthropic).'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

# JWT session policy
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_ACCESS_MINUTES', '30'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

if _TESTING:
    # Tests hash a lot of throwaway secrets (passwords, 2FA recovery codes).
    # PBKDF2 is deliberately slow, which is right in production and pure waste
    # here — this keeps the suite from spending most of its time stretching
    # keys nobody will ever attack.
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Logging: print finance_api logs (AI calls, auth) to the runserver console.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'finance_api': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
